#!/usr/bin/env bash
#displays "bad luck" for the 4th loop iteration
#displays "good luck" for the 8th loop iteration
#displays "Best School" for the other iterations
#5-4_bad_luck_8_is_your_chance

counter=1

while ((counter <= 10)); do
	if ((counter == 4));
	then
		echo bad luck
	elif ((counter == 8));
	then
		echo good luck
	else
		echo Best School
	fi
	((counter++));
done
