#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
#7-clock

Hour=0
while ((Hour <= 12)); do
	echo Hour: $Hour
	minute=1
	while ((minute <= 59)); do
		echo $minute
		((minute++));
	done
	((Hour++));
done
