#!/usr/bin/env bash
#Gives you information about the "school file". Display
#if the file exists: school file exists
#if the file does not exist: school file does not exist
#If the file exists, print:
#if the file is empty: school file is empty
#if the file is not empty: school file is not empty
#if the file is a regular file: school is a regular file
#if the file is not a regular file: (nothing)
#9-to_file_or_not_to_file

t_file=school

if test -e "$t_file"; then
	echo $t_file file exists
	if test -s "$t_file"; then
		echo $t_file file is not empty
	else
		echo $t_file file is empty
	fi
	if test -f "$t_file"; then
		echo $t_file is a regular file
	fi
else
	echo $t_file file does not exist
fi
